### ISSUE TITLE
Validate webhook using signature instead of re-fetching the event

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-stripe-light#523]
#### Issue Summary

Stripe [now provides webhook signatures](https://stripe.com/docs/webhooks#signatures) so we can drop the old method of protecting against fake events posting to our endpoint by validating the event using the signature.

**Comment by tstirrat15** [comment]
@tysonclugg what's the status of your branch? Will it be going to PR soon? As an interested user, I'd love to see this in a release.

**Comment by tysonclugg** [comment]
@tstirrat15 I had [some questions](#567) regarding updating the docs, which are partially answered.  Aside from the docs, my branch is ready for review.
I've been snowed under at work and this got sidelined, but I may have some time today to finish the documentation updates and submit my branch for review.

**Comment by tstirrat15** [comment]
@tysonclugg any updates?

**Comment by tysonclugg** [comment]
@tstirrat15 I'll have a look on Monday.

**Comment by paltman** [comment]
Done in 0d6da79324e62fd488ed936c8d6a3ba4edbb8807
