### ISSUE TITLE
Missing webhook handlers

### ISSUE THREAD

**Issue by tysonclugg** [pinax/pinax-stripe-light#541]
The following webhooks have no handlers registered in `pinax.stripe.webhooks.registry`:

 - [ ] `charge.pending`
 - [ ] `charge.refund.updated`
 - [ ] `customer.bank_account.deleted`
 - [ ] `customer.source.expiring`
 - [ ] `file.created`
 - [ ] `invoice.sent`
 - [ ] `invoice.upcoming`
 - [ ] `order_return.created`
 - [ ] `payout.canceled`
 - [ ] `payout.created`
 - [ ] `payout.failed`
 - [ ] `payout.paid`
 - [ ] `payout.updated`
 - [ ] `product.deleted`
 - [ ] `review.closed`
 - [ ] `review.opened`
 - [ ] `sigma.scheduled_query_run.created`
 - [ ] `sku.deleted`
 - [ ] `source.canceled`
 - [ ] `source.chargeable`
 - [ ] `source.failed`
 - [ ] `source.transaction.created`

This feature request is important because it's not currently possible to receive signals for any missing events.

**Comment by blueyed** [comment]
How did you compile the list?
Would it be possible to do this automatically, e.g. by scraping the docs?

**Comment by tysonclugg** [comment]
@blueyed I opened up Chrome Dec tools while looking at the Store docs to find the XHR call to the Stripe website that includes the relevant docs. I was thinking the same as you and tried to write a script, it got complicated...

**Comment by paltman** [comment]
I've implemented some codegen for this with https://github.com/pinax/pinax-stripe/blob/bca0b591c1c8dccb176e444d32ac8ba164c49e78/update_webhooks.py#L1
